### ISSUE TITLE
Sound works but volume keys don't [SOLVED] + localized keyboard [WORKAROUND] 

### ISSUE THREAD

**Issue by matt32106** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#20]
Hi,
i installed ubuntu 16.10 with updates then ran the script e200ha_with_sound.sh 

After reboot, i made sure i was running custom3 kernel.

Firefox > youtube, at first no sound. I went into the gnome widget and played with the sliders of the different options and bingo > sound ! :) (enjoy the silence from depeche mode seemed appropriate for some reason... :))

I have one issue now, the fn vol up / vol down keys don't seem to work, am i alone?

The only difference from gnome vanilla 16.10 is that i ran the language option to get a french keyboard. 

Thanks for the hardwork :)

**Comment by matt32106** [comment]
the culprit is the keyboard change, i switched back to the english keyboard, problem solved

**Comment by Grippy98** [comment]
Glad you managed to get it working :) 

Yeah this can be added to the list of weird and annoying issues haha. I remember trying to remap the keys but due to the way the keyboard reports the special function modifier I don't think that's super easy to do at the moment... maybe something like a Autohotkey port for Linux.

Hope it's not a dealbreaker for you to use QWERTY for right now...

**Comment by matt32106** [comment]
well, this is strange, i used 
`setxkbmap fr`
and everything works as far as i can tell, hooray! i have my localized keyboard and function keys work :)

*ubuntu 16.10 
uname -r  = 4.12.0-rc1-custom3*

**Comment by Grippy98** [comment]
Glad you got it working! :)
