### ISSUE TITLE
Regression on new Ubuntu 17:10 release? [WiFi][Atheros firmware bug]

### ISSUE THREAD

**Issue by ilpiero** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#27]
Hello,

This is not really a bug, but since this is an useful resource for the E200HA owner here, I tough itcoudl be useful to post.

I tested the script on ubuntu 17.04, without noticeable issues.
Now I tested a fresh install of 17.10 , before doing any modifications i can say that the "out of the box" experience is worse.

`
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

Audio is still not working (it's ok we knew it...) but i get the kernel log flooded with:
`[  223.819159]  Audio Port: ASoC: no backend DAIs enabled for Audio Port`

Some processes are hanging the kernel and the shutdown takes minutes to perform
`uname -a
Linux marco-E200HA 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
there is a kernel process hung, plus network manager and the wpa supplicant
`
[  363.462128] INFO: task kworker/u8:3:203 blocked for more than 120 seconds.
[  363.462151]       Not tainted 4.13.0-16-generic #19-Ubuntu
[  363.462162] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
`
On top of this i get also a warning about the high cpu load/temperature

... i will keep troubleshooting.

**Comment by Lucassifoni** [comment]
Same here, it happened last week (I'm running mainline 17.10 since alpha 2). It's impossible to switch networks after opening a session.
The high CPU warning is a bit odd, I get the same, but battery doesn't discharge faster and the laptop stays cool.
Did you manage to shutdown properly ? I'm stuck pressing the power button for more than 15 seconds, shutdown results in an endless shutdown screen and CPU temp warnings.

**Comment by svmagic** [comment]
I hope this may help you.

I think I had a similar problem. I installed Xubuntu 17.10 on my L200ha. When I tried to disconnect the WiFi connection, my L200ha froze. Because of this, it also took a while to shut off the laptop.

I replaced the firmware for Wifi(and Bluetooth). I downloaded a new firmware(<https://github.com/kvalo/ath10k-firmware/blob/master/QCA9377/hw1.0/WLAN.TF.1.0/firmware-5.bin_WLAN.TF.1.0-00002-QCATFSWPZ-5>), replaced the existing one(`/lib/firmware/ath10k/QCA9377/hw1.0/firmware05.bin`) with it, and commanded `sudo rmmod ath10k_pci` & `sudo modprobe -v ath10k_pci`. Now it works well. Unlike before, my Bluetooth keyboard is well paired, too.

**Comment by Lucassifoni** [comment]
@svmagic thanks ! I'll have to get more context on this since I'm not too keen of throwing a random blob on my computer, but it's nice of you :)

**Comment by ilpiero** [comment]
Thanks a lot! The annoying shutdown problem is gone and also the networking works better.
How did you know? Was it a known bug of the wifi chip driver?
:)

**Comment by svmagic** [comment]
@Lucassifoni I googled, and found that "the ath10k firmware images are available from [linux-firmware.git](https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/) which all common Linux distributions should install by default", and that "latest firmware images can be downloaded from [ath10k-firmware.git](https://github.com/kvalo/ath10k-firmware) from which they get eventually pushed to [linux-firmware.git](https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/)."([Linux Wireless wiki](https://wireless.wiki.kernel.org/en/users/drivers/ath10k/firmware)). So, I guess the firmware is a relatively reliable one.

I don't know exactly what the problem was. I found [an interesting comment](https://github.com/kvalo/ath10k-firmware/commit/838fb552d6ab82c012d2f0df97954d35c0c987ad) in [ath10k-firmware.git](https://github.com/kvalo/ath10k-firmware) which said that,

```
QCA9377 hw1.0: rename firmware-5.bin_WLAN.TF.1.0-00267-1 to firmware-…
…5.bin_CNSS.TF.1.0-00267-QCATFSWPZ-1

The version string for this release was actually, the name of firmware branch
was actually CNSS.TF.1.0. This was noticed when the real WLAN.TF.1.0 branch was
created.

So rename the existing firmare image to match the correct firmware branch:

git mv firmware-5.bin_WLAN.TF.1.0-00267-1 firmware-5.bin_CNSS.TF.1.0-00267-QCATFSWPZ-1
ath10k-fwencoder --modify \
 --firmware-version=CNSS.TF.1.0-00267-QCATFSWPZ-1 \
 firmware-5.bin_CNSS.TF.1.0-00267-QCATFSWPZ-1
 ```

 So, I guess that there was an incorrect version which has been packaged with distributions. Because it's been a few days since I first used GNU/Linux, my guess could be *completely wrong*.

 @ilpiero I was just lucky. I use a very old (10-year-old) wireless router at home, and there was no problem when I connected to this. But, every time I tried to connect to a Wifi hotspot or a public Wifi and disconnect it, my laptop froze. So, I guessed that the firmware does not handle Wifi properly with certain standards.

**Comment by ilpiero** [comment]
Good job! I'm 100% confident about the problem and the solution.
I find strange that googling does not give any result about it, what would the best place be to put a description of this bug?

Thanks Again!

**Comment by Lucassifoni** [comment]
@svmagic @ilpiero Thanks a lot for your research and testing. It's perfect.

I'm sure this thread will get some traffic, I've seen reports of that same Atheros firmware bug popping on Reddit & Twitter.

**Comment by ilpiero** [comment]
I'll mark this as closed and put a meaningful title. 
Thanks guys!

**Comment by Grippy98** [comment]
Awesome detective work! Thanks for posting about it!
