### ISSUE TITLE
Ubuntu 17.04 works fine. What about security update notifications?

### ISSUE THREAD

**Issue by Shemzone** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#28]
Hi there. 
I gave it a new try and it works (Asus X206HA). Ciao Windows 10 for now!
As I said in the title, everything works fine with Ubuntu 17.04 (the only distro actually, and I tested a lot). I checked the Ubuntu updates via the Update Manager and I see there is a lot of security updates to apply.
Could I apply them with no risk to lose everything which has been added by the custom kernel (4.12-rc6)?
Thanks for your advices and happy Christmas or whatever you believe in.

**Comment by Grippy98** [comment]
Hey, sorry for the delay in replying!

As long as you make sure you always revert back to the custom kernel and only update other stuff you should be fine. You'll be missing out on kernel security patches but otherwise you should be fine. You don't really risk losing everything as you can always change the kernel from the grub boot menu. 

Merry Christmas to you too!

**Comment by Shemzone** [comment]
Hi Andrei, thank you for your reply, no matter of the delay :-) 
So if I understood correctly, once yhe updates, I have to install again your kernel or will it remaining installed and switchable  to it from the Grub menu?

**Comment by Grippy98** [comment]
It should remain switchable from the grub menu!

**Comment by Shemzone** [comment]
Ok, thank you. I'm going try right now
